name: Build and Tests on Windows with MSVC

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set VCPKG_ROOT
      run: echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" | Out-File -FilePath $env:GITHUB_ENV -Append

    - name: Get CMake and vcpkg versions
      run: |
        cmake --version
        echo "---"
        echo "VCPKG_ROOT is $env:VCPKG_ROOT"
        vcpkg --version

    - name: Configure CMake
      run: cmake -B ./build -DCMAKE_CXX_COMPILER=cl -DCMAKE_BUILD_TYPE=Release -S .

    - name: Build project
      run: cmake --build ./build
      
    - name: Run Tests with CTest
      working-directory: ./build
      run: ctest